### PR TITLE
Allow type registration as the way to find collections for node syncing.

### PR DESCRIPTION
**Pull request by queso**
/cc @bfodeke @shrop

### CODE REVIEW

**Comment by queso** [comment]
So this is what I was thinking as a way to sync data into proper Meteor collections instead of one monolithic collection.

Basically inside a collection file you can add:

```
DrupalDdp.registerType('objective', Objectives)
```

And that tells it to insert any node with a type of `objective` into the `Objectives` collection. I think this helps make everything cleaner from a client-side perspective in Meteor. Now I can say Objectives.find({nid: 1234}) and return what we need, then I can use things like objective.title, etc.

As a Meteor app writer, I shouldn't be concerned that the data came from Drupal via a package into one big collection, but instead just write my Meteor app like a normal app with collections. This will make maintainability better down the road for clients.

**Comment by shrop** [comment]
@queso How would we handle updates to data from Drupal? Similarly? I am good with this direction.

**Comment by queso** [comment]
@shrop I am not sure I follow, the code has stuff in place to handle inserts, removals, and updates.

See https://github.com/hb5co/drupal-ddp/pull/11/files#diff-22e17ca8d9908ff2be4e2942687c18c6R21

**Comment by shrop** [comment]
lol. ok. missed it.. @bfodeke going to get this in there. Please test this update with Drupal DDP on your end and see if Drupal module changes are needed. Should be pretty good though. I guess your test app needs to add the registration for collections though.

**Comment by bfodeke** [comment]
Will do. I'll test and report

**Pull request merged**
